/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-latency_manager
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_LATENCY_MANAGER_API_H
#define INCLUDED_LATENCY_MANAGER_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_latency_manager_EXPORTS
#define LATENCY_MANAGER_API __GR_ATTR_EXPORT
#else
#define LATENCY_MANAGER_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_LATENCY_MANAGER_API_H */
