FROM archlinux:latest AS base

# Install everything except cmake
RUN pacman -Suy --noconfirm base-devel cmake git boost gnuradio gnuradio-osmosdr libuhd


# GNURadio requires a place to store some files, can only be set via $HOME env var.
ENV HOME=/tmp

CMD ["/usr/local/bin/trunk-recorder", "--config=/app/config.json"]
